src/ConversionPath/Pages/Conversion.cshtml.cs
using ConversionPath.Application.ExchangeRates.Queries;
using ConversionPath.Domain.Contracts;
using ConversionPath.Shared.Dtos;
using ConversionPath.Shared.Dtos.ExchangeRates;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConversionPath.Pages;

public class Conversion : PageModel
{
    private readonly ICurrencyConverter _converter;
    private readonly IMediator _mediator;

    private ICollection<ExchangeRateDto> _rates { get; set; }

    public Conversion(ICurrencyConverter converter, IMediator mediator)
    {
        _converter = converter;
        _mediator = mediator;
    }
    [BindProperty]
    public string SourceCurrency { get; set; }
    [BindProperty]
    public string DestinationCurrency { get; set; }
    [BindProperty]
    public double Amount { get; set; }
    
    public ConversionResultDto ConversionResult { get; set; }
    
    public async Task OnGetAsync()
    {
        SourceCurrency = "BNB";
        DestinationCurrency = "IRR";
        Amount = 0.5;

        _rates = await _mediator.Send(new GetAllExchangeRatesQuery());
        _converter.SetRates(_rates);
    }
    
    public async Task OnPostSubmit()
    {
        ConversionResult = await _converter.Convert(SourceCurrency, DestinationCurrency, Amount);
    }
}

src/ConversionPath/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ConversionPath.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/ConversionPath/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConversionPath.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/ConversionPath/Pages/ListOfExchangeRates.cshtml.cs
using ConversionPath.Application.ExchangeRates.Queries;
using ConversionPath.Shared.Dtos.ExchangeRates;
using MediatR;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConversionPath.Pages.ExchangeRates
{
    public class ListOfExchangeRatesModel : PageModel
    {
        protected readonly IMediator _mediator;
        public IEnumerable<ExchangeRateDto> Rates;

        public ListOfExchangeRatesModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync()
        {
            Rates = await _mediator.Send(new GetAllExchangeRatesQuery());
        }
    }
}

src/ConversionPath/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConversionPath.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/ConversionPath/Pages/Conversion.cshtml
@page
@using ConversionPath.Domain.Contracts
@model ConversionPath.Pages.Conversion

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <form method="post">
        <table class="table">
            <tr>
                <td>Source Currency</td>
                <td><input type="text" id="sourceCurrency" name="SourceCurrency"/></td>
            </tr>
            <tr>
                <td>Destination Currency</td>
                <td><input type="text" id="destinationCurrency" name="DestinationCurrency"/></td>
            </tr>
            <tr>
                <td>Amount</td>
                <td><input type="number" id="amount" name="Amount"/></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Convert" asp-page-handler="Submit"/></td>
            </tr>
        </table>
        <hr/> 
    </form>
    @if (Model.ConversionResult != null)
    {
        <p>@Model.ConversionResult.Result.ToString()</p>
    }
</div>
</body>
</html>

src/ConversionPath/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/ConversionPath/Pages/ListOfExchangeRates.cshtml
@page
@model ConversionPath.Pages.ExchangeRates.ListOfExchangeRatesModel
@{
    @foreach(var item in Model.Rates)
    {
        <p>@item.SourceDestinationString - <strong>@item.Rate</strong></p>
        <br/>
    }
}

src/ConversionPath/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConversionPath</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConversionPath.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ConversionPath</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ListOfExchangeRates">Exchange Rates</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Conversion">Conversion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ConversionPath - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>